##  A MAKEFILE FOR The Ancestry HMM. TO USE, RUN THE COMMAND "make" VIA COMMAND LINE ##

all:
## IF TCMALLOC IS NOT INSTALLED, COMMENT OUT THE FOLLOWING LINE 
## BY PLACING A # IN FRONT OF THE FOLLOWING LINE AND REMOVE '#' ON THE NEXT LINE
	$(LINK.cc) -std=c++11 -O3 -o ibd_hmm ibd_hmm.cpp
